version: '2'

services:


  ##################  Esn Admin ##################
  esn-admin:
    container_name: esn-admin
    image: {{aws.dtr:738739307270.dkr.ecr.eu-west-1.amazonaws.com}}/easyms-admin:@app.version@
    environment:
      SPRING_PROFILES_ACTIVE: dev
      JAVA_OPTS: -Xms128m -Xmx256m -XX:MaxRAM=500m
      JVM_GC_THREADS: 2
      PROJECT_ID: esn
      app.id: esn-admin
    ports:
      - 2003:2003
    logging:
      driver: awslogs
      options:
        awslogs-group: esn-logs
        awslogs-region: eu-west-1
        awslogs-stream-prefix: esn-admin