version: "2"

services:


  ################# Easyms Oauth2 ####################
  easyms-oauth2:
    container_name: easyms-oauth2
    image: 738739307270.dkr.ecr.eu-west-1.amazonaws.com/easyms-oauth2:@app.version@
    environment:
      SPRING_PROFILES_ACTIVE: prod
      HEALTHCHECK_PORT: 2000
      HEALTHCHECK_NEXT_EXECUTION: 5
      JAVA_OPTS: -Xms128m -Xmx256m
      JVM_GC_THREADS: 2
      PROJECT_ID: esn
      app.id: easyms-oauth2
    ports:
      - 2000:2000
    logging:
      driver: awslogs
      options:
        awslogs-group: {{aws.log.group}}
        awslogs-region: {{aws.region}}
        awslogs-stream-prefix: easyms-oauth2