version: 1
task_definition:
  ecs_network_mode: awsvpc
  task_execution_role: ecsTaskExecutionRole
  task_size:
    mem_limit: {{aws.task.mem.limit}}
    cpu_limit: {{aws.task.cpu.limit}}
run_params:
  network_configuration:
    awsvpc_configuration:
      subnets:
        - "{{aws.subnet.priv1:subnet-00d32181a9269e25c}}"
        - "{{aws.subnet.priv2:subnet-0a9864e9b59d91aa1}}"
      security_groups:
        - {{oauth2.aws.security-group}}
      assign_public_ip: DISABLED